select FILES.server_location as file_server_location,
    FILES.google_drive_location as file_google_drive_location,
    DDC."name" as column_name,
    array_to_string( array_agg( distinct FORM_DIRS.server_path || '/' || CF."name" ), ', ' ) as forms
from (
    VALUES ('CPA_ACCT_HIST', 'actrisk'),
        ('CPA_ACCT_HIST', 'actin_date'), 
        ('CPA_ACCT_HIST', 'carrier'),
        ('CPA_ACCT_HIST', 'actpolicy_num'),
        ('CPA_ACCT_HIST', 'act_code'),
        ('CPA_ACCT_HIST', 'act_chrgdate'),
        ('CPA_ACCT_HIST', 'net_sec'),
        ('CPA_ACCT_HIST', 'net_sec_pct'),
        ('CPA_ACCT_HIST', 'cyber'),
        ('CPA_ACCT_HIST', 'cyber_prem'),
        ('CPA_HIST', 'risk_num'),
        ('CPA_HIST', 'policy_num'),
        ('CPA_HIST', 'inception_date'),
        ('CPA_HIST', 'select_2yr'),
        ('CPA_HIST', 'first_ga_date'),
        ('CPA_HIST', 'state'),
        ('CPA_HIST', 'county'),
        ('CPA_HIST', 'establish_date'),
        ('CPA_HIST', 'gross_revenue'),
        ('CPA_HIST', 'cpas'),
        ('CPA_HIST', 'professionals'),
        ('CPA_HIST', 'part_time'),
        ('CPA_HIST', 'premium_total'),
        ('CPA_HIST', 'claim_expenses'),
        ('CPA_HIST', 'step'),
        ('CPA_HIST', 'ded_damage_only'),
        ('CPA_HIST', 'over_50_pct'),
        ('CPA_HIST', 'deductible'),
        ('CPA_CUSTOMER', 'risk_num'),
        ('CPA_CUSTOMER', 'dead_file_reasn'),
        ('CPA_CUSTOMER', 'bipd'),
        ('CPA_CUSTOMER', 'rating_flags'),
        ('CPA_CUSTOMER', 'padin1'),
        ('CPA_CUSTOMER', 'padin2'),
        ('CPA_CUSTOMER', 'limit_purchased'),
        ('CPA_CUSTOMER', 'deductible'),
        ('CPA_CUSTOMER', 'embz'),
        ('CPA_CUSTOMER', 'binder_no'),
        ('CPA_CUSTOMER', 'linked_carriers'),
        ('CPA_CUSTOMER', 'policy_num'),
        ('CPA_CUSTOMER', 'ft_admin'),
        ('CPA_CUSTOMER', 'pt_admin'),
        ('CPA_CUSTOMER', 'cyber_opt'),
        ('CPA_CUSTOMER', 'cyber_lim_std'),
        ('CPA_CUSTOMER', 'cyber_ret'),
        ('CPA_CUSTOMER', 'supp_payopt_b'),
        ('CPA_CUSTOMER', 'supp_payopt_c'),
        ('CPA_CUSTOMER', 'inception_date'),
        ('CPA_CUSTOMER', 'cyber_prior_act'),
        ('CPA_CUSTOMER', 'int_pad_arr'),
        ('CPA_GASLIDER', 'risk_num'),
        ('CPA_GASLIDER', 'aop_low'),
        ('CPA_GASLIDER', 'aop_mid'),
        ('CPA_GASLIDER', 'aop_hi'),
        ('CPA_PRACTICE', 'risk_num'),
        ('CPA_PRACTICE', 'pct'),
        ('CPA_PRACTICE', 'pub'),
        ('CPA_PRACTICE', 'irms'),
        ('CPA_LEIN', 'risk_num'),
        ('CPA_LEIN', 'surch'),
        ('CPA_LEIN', 'pad1'),
        ('CPA_LEIN', 'base_prem')
) REP (conetic_data_file, column_name)
join (
    VALUES ('CPA_ACCT_HIST', '/usr3/interacct/data/acctrxi', 'CPA_ACCOUNTING/acctrxi.csv'),
        ('CPA_HIST', '/usr3/inter/data/histi', 'CPA/histi.csv'),
        ('CPA_CUSTOMER', '/usr3/inter/data/icustomer', 'CPA/icustomer.csv'),
        ('CPA_GASLIDER', '/usr3/inter/data/GAslider', 'CPA/GAslider.csv'),
        ('CPA_PRACTICE', '/usr3/inter/data/GApractice', 'CPA/GApractice.csv'),
        ('CPA_LEIN', '/usr3/inter/data/lein', 'CPA/lein.csv')
) FILES (conetic_data_file, server_location, google_drive_location) on REP.conetic_data_file = FILES.conetic_data_file
left join data_definition DD on REP.conetic_data_file = DDC.conetic_data_file
left join data_definition_column DDC on DD.id = DDC.data_definition_id and (DDC."name" = REP.column_name or DDC."name" like REP.column_name || '[%]')
left join column_conetic_forms CCF on DDC.id = CCF.column_id
left join conetic_form CF on CF.id = CCF.conetic_form_id
left join (
    ('CPA_UNDERWRITER', '/usr3/inter/scr'),
    ('RE_UNDERWRITER', '/usr2/inter/scr'),
    ('RE_ACCOUNTING', '/usr2/interacct/scr'),
    ('CPA_ACCOUNTING', '/usr3/interacct/scr'),
    ('LAWYERS_UNDERWRITER', '/usr2/law/scr'),
    ('LAWYERS_ACCOUNTING', '/usr2/law/accounting/scr'),
    ('MISC_UNDERWRITER', '/usr3/misc/scr'),
    ('MISC_ACCOUNTING', '/usr3/miscacct/scr'),
    ('CPA_MGT', '/usr3/inter/mgt/scr'),
    ('CPA_UTILITY', '/usr3/inter/rpt/UTILITY'),
    ('RE_PROCESSING', '/usr2/inter/process/scr'),
    ('LA_PROCESSING', '/usr2/law/process/scr'),
    ('RE_GS_CLAIMS', '/usr2/inter/gsclaims/scr'),
    ('CPA_IIG_CLAIMS', '/usr3/inter/iigclaim/scr'),
    ('RE_NV_CLAIMS', '/usr2/inter/nvclaims/scr'),
    ('RE_IIG_CLAIMS', '/usr2/inter/iigclaim/scr'),
    ('RE_GA_CLAIMS', '/usr2/inter/gaclaims/scr'),
    ('CPA_GS', '/usr3/inter/scr/GS'),
    ('RE_GS', '/usr2/inter/scr/GS')
) FORM_DIRS (conetic_form_directory, server_path) on CF.conetic_form_directory = FORM_DIRS.conetic_form_directory
group by FILES.server_location,
    FILES.google_drive_location,
    DDC."name"
order by FILES.google_drive_location,
    DDC."name"
